Repository GoogleCloudPlatform/flink-on-k8s-operator, pull requests merged in 2019-10, with the labels that each got.

#52 Add doc on submitting jobs with port forwarding
  docs/developer-guide.md
Labels: documentation

#45 Add ingress resource
  api/v1alpha1/flinkcluster_default.go
  api/v1alpha1/flinkcluster_default_test.go
  api/v1alpha1/flinkcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml
  config/rbac/role.yaml
  controllers/flinkcluster_controller.go
  controllers/flinkcluster_converter.go
  controllers/flinkcluster_converter_test.go
  controllers/flinkcluster_observer.go
  controllers/flinkcluster_reconciler.go
  controllers/flinkcluster_updater.go
  docs/crd.md
  main.go
Labels: feature

#74 Add unit test for TimeConverter
  controllers/flinkcluster_util_test.go
Labels: test
